# CROSS COMPILER SETTING
SET(CMAKE_SYSTEM_NAME Generic)
CMAKE_MINIMUM_REQUIRED (VERSION 3.10.0)

# THE VERSION NUMBER
SET (Tutorial_VERSION_MAJOR 1)
SET (Tutorial_VERSION_MINOR 0)

if (DEFINED ENV{SdkRootDirPath})
	SET(SdkRootDirPath "$ENV{SdkRootDirPath}")
endif()

if (NOT DEFINED SdkRootDirPath)
	MESSAGE(FATAL_ERROR "SDK path could not be determined. Please update SdkRootDirPath value from your CMake presets file(s).")
endif()

# ENABLE ASM
ENABLE_LANGUAGE(ASM)

# RESET FLAG VALUES
SET(CMAKE_ASM_FLAGS_DEBUG "")
SET(CMAKE_ASM_FLAGS_RELEASE "")
SET(CMAKE_C_FLAGS_DEBUG "")
SET(CMAKE_C_FLAGS_RELEASE "")
SET(CMAKE_CXX_FLAGS_DEBUG "")
SET(CMAKE_CXX_FLAGS_RELEASE "")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE "")

# CURRENT DIRECTORY
SET(ProjDirPath ${CMAKE_CURRENT_SOURCE_DIR})

SET(EXECUTABLE_OUTPUT_PATH ${ProjDirPath}/${CMAKE_BUILD_TYPE})
SET(LIBRARY_OUTPUT_PATH ${ProjDirPath}/${CMAKE_BUILD_TYPE})

set(CMAKE_USER_MAKE_RULES_OVERRIDE "user_override.cmake")

project(MCXN947_Web_Based_Data_Logger)
set(MCUX_SDK_PROJECT_NAME MCXN947_Web_Based_Data_Logger)

include(${ProjDirPath}/flags.cmake)

add_executable(${MCUX_SDK_PROJECT_NAME} "${ProjDirPath}/CMSIS/tz_context.h"
"${ProjDirPath}/CMSIS/core_cm33.h"
"${ProjDirPath}/CMSIS/cmsis_version.h"
"${ProjDirPath}/CMSIS/cmsis_gcc.h"
"${ProjDirPath}/CMSIS/cmsis_compiler.h"
"${ProjDirPath}/CMSIS/m-profile/cmsis_gcc_m.h"
"${ProjDirPath}/CMSIS/m-profile/armv8m_mpu.h"
"${ProjDirPath}/CMSIS_driver/Include/Driver_USART.h"
"${ProjDirPath}/CMSIS_driver/Include/Driver_SPI.h"
"${ProjDirPath}/CMSIS_driver/Include/Driver_I2C.h"
"${ProjDirPath}/CMSIS_driver/Include/Driver_Common.h"
"${ProjDirPath}/CMSIS_driver/Include/GPIO/Driver_GPIO.h"
"${ProjDirPath}/app/Temp/temp.h"
"${ProjDirPath}/app/Temp/temp.c"
"${ProjDirPath}/app/Led_Indicators/Led_Indicators.h"
"${ProjDirPath}/app/Led_Indicators/Led_Indicators.c"
"${ProjDirPath}/board/pin_mux.h"
"${ProjDirPath}/board/pin_mux.c"
"${ProjDirPath}/board/peripherals.h"
"${ProjDirPath}/board/peripherals.c"
"${ProjDirPath}/board/clock_config.h"
"${ProjDirPath}/board/clock_config.c"
"${ProjDirPath}/board/board.h"
"${ProjDirPath}/board/board.c"
"${ProjDirPath}/board/RTE_Device.h"
"${ProjDirPath}/component/fsl_silicon_id_soc.h"
"${ProjDirPath}/component/uart/fsl_adapter_uart.h"
"${ProjDirPath}/component/uart/fsl_adapter_lpuart.c"
"${ProjDirPath}/component/silicon_id/fsl_silicon_id_soc.c"
"${ProjDirPath}/component/silicon_id/fsl_silicon_id.h"
"${ProjDirPath}/component/silicon_id/fsl_silicon_id.c"
"${ProjDirPath}/component/serial_manager/fsl_component_serial_port_uart.h"
"${ProjDirPath}/component/serial_manager/fsl_component_serial_port_uart.c"
"${ProjDirPath}/component/serial_manager/fsl_component_serial_port_internal.h"
"${ProjDirPath}/component/serial_manager/fsl_component_serial_manager.h"
"${ProjDirPath}/component/serial_manager/fsl_component_serial_manager.c"
"${ProjDirPath}/component/lists/fsl_component_generic_list.h"
"${ProjDirPath}/component/lists/fsl_component_generic_list.c"
"${ProjDirPath}/component/gpio/fsl_adapter_gpio.h"
"${ProjDirPath}/component/gpio/fsl_adapter_gpio.c"
"${ProjDirPath}/component/phy/fsl_phy.h"
"${ProjDirPath}/device/system_MCXN947_cm33_core0.h"
"${ProjDirPath}/device/system_MCXN947_cm33_core0.c"
"${ProjDirPath}/device/fsl_device_registers.h"
"${ProjDirPath}/device/MCXN947_cm33_core0_features.h"
"${ProjDirPath}/device/MCXN947_cm33_core0_COMMON.h"
"${ProjDirPath}/device/MCXN947_cm33_core0.h"
"${ProjDirPath}/device/periph/PERI_WWDT.h"
"${ProjDirPath}/device/periph/PERI_WUU.h"
"${ProjDirPath}/device/periph/PERI_VREF.h"
"${ProjDirPath}/device/periph/PERI_VBAT.h"
"${ProjDirPath}/device/periph/PERI_UTICK.h"
"${ProjDirPath}/device/periph/PERI_USDHC.h"
"${ProjDirPath}/device/periph/PERI_USBPHY.h"
"${ProjDirPath}/device/periph/PERI_USBNC.h"
"${ProjDirPath}/device/periph/PERI_USBHSDCD.h"
"${ProjDirPath}/device/periph/PERI_USBHS.h"
"${ProjDirPath}/device/periph/PERI_USBDCD.h"
"${ProjDirPath}/device/periph/PERI_USB.h"
"${ProjDirPath}/device/periph/PERI_TSI.h"
"${ProjDirPath}/device/periph/PERI_TRDC.h"
"${ProjDirPath}/device/periph/PERI_SYSPM.h"
"${ProjDirPath}/device/periph/PERI_SYSCON.h"
"${ProjDirPath}/device/periph/PERI_SPC.h"
"${ProjDirPath}/device/periph/PERI_SMARTDMA.h"
"${ProjDirPath}/device/periph/PERI_SINC.h"
"${ProjDirPath}/device/periph/PERI_SEMA42.h"
"${ProjDirPath}/device/periph/PERI_SCT.h"
"${ProjDirPath}/device/periph/PERI_SCG.h"
"${ProjDirPath}/device/periph/PERI_S50.h"
"${ProjDirPath}/device/periph/PERI_RTC.h"
"${ProjDirPath}/device/periph/PERI_QDC.h"
"${ProjDirPath}/device/periph/PERI_PWM.h"
"${ProjDirPath}/device/periph/PERI_PUF.h"
"${ProjDirPath}/device/periph/PERI_POWERQUAD.h"
"${ProjDirPath}/device/periph/PERI_PORT.h"
"${ProjDirPath}/device/periph/PERI_PLU.h"
"${ProjDirPath}/device/periph/PERI_PKC.h"
"${ProjDirPath}/device/periph/PERI_PINT.h"
"${ProjDirPath}/device/periph/PERI_PDM.h"
"${ProjDirPath}/device/periph/PERI_OTPC.h"
"${ProjDirPath}/device/periph/PERI_OSTIMER.h"
"${ProjDirPath}/device/periph/PERI_OPAMP.h"
"${ProjDirPath}/device/periph/PERI_NPX.h"
"${ProjDirPath}/device/periph/PERI_MRT.h"
"${ProjDirPath}/device/periph/PERI_MAILBOX.h"
"${ProjDirPath}/device/periph/PERI_LP_FLEXCOMM.h"
"${ProjDirPath}/device/periph/PERI_LPUART.h"
"${ProjDirPath}/device/periph/PERI_LPTMR.h"
"${ProjDirPath}/device/periph/PERI_LPSPI.h"
"${ProjDirPath}/device/periph/PERI_LPI2C.h"
"${ProjDirPath}/device/periph/PERI_LPDAC.h"
"${ProjDirPath}/device/periph/PERI_LPCMP.h"
"${ProjDirPath}/device/periph/PERI_ITRC.h"
"${ProjDirPath}/device/periph/PERI_INTM.h"
"${ProjDirPath}/device/periph/PERI_INPUTMUX.h"
"${ProjDirPath}/device/periph/PERI_I3C.h"
"${ProjDirPath}/device/periph/PERI_I2S.h"
"${ProjDirPath}/device/periph/PERI_HPDAC.h"
"${ProjDirPath}/device/periph/PERI_GPIO.h"
"${ProjDirPath}/device/periph/PERI_GDET.h"
"${ProjDirPath}/device/periph/PERI_FREQME.h"
"${ProjDirPath}/device/periph/PERI_FMUTEST.h"
"${ProjDirPath}/device/periph/PERI_FMU.h"
"${ProjDirPath}/device/periph/PERI_FLEXSPI.h"
"${ProjDirPath}/device/periph/PERI_FLEXIO.h"
"${ProjDirPath}/device/periph/PERI_EWM.h"
"${ProjDirPath}/device/periph/PERI_EVTG.h"
"${ProjDirPath}/device/periph/PERI_ERM.h"
"${ProjDirPath}/device/periph/PERI_ENET.h"
"${ProjDirPath}/device/periph/PERI_EMVSIM.h"
"${ProjDirPath}/device/periph/PERI_EIM.h"
"${ProjDirPath}/device/periph/PERI_DMA.h"
"${ProjDirPath}/device/periph/PERI_DM.h"
"${ProjDirPath}/device/periph/PERI_DIGTMP.h"
"${ProjDirPath}/device/periph/PERI_CTIMER.h"
"${ProjDirPath}/device/periph/PERI_CRC.h"
"${ProjDirPath}/device/periph/PERI_CMC.h"
"${ProjDirPath}/device/periph/PERI_CDOG.h"
"${ProjDirPath}/device/periph/PERI_CAN.h"
"${ProjDirPath}/device/periph/PERI_CACHE64_POLSEL.h"
"${ProjDirPath}/device/periph/PERI_CACHE64_CTRL.h"
"${ProjDirPath}/device/periph/PERI_BSP32.h"
"${ProjDirPath}/device/periph/PERI_AHBSC.h"
"${ProjDirPath}/device/periph/PERI_ADC.h"
"${ProjDirPath}/drivers/fsl_wwdt.h"
"${ProjDirPath}/drivers/fsl_wwdt.c"
"${ProjDirPath}/drivers/fsl_spc.h"
"${ProjDirPath}/drivers/fsl_spc.c"
"${ProjDirPath}/drivers/fsl_reset.h"
"${ProjDirPath}/drivers/fsl_reset.c"
"${ProjDirPath}/drivers/fsl_port.h"
"${ProjDirPath}/drivers/fsl_lpuart_edma.h"
"${ProjDirPath}/drivers/fsl_lpuart_edma.c"
"${ProjDirPath}/drivers/fsl_lpuart_cmsis.h"
"${ProjDirPath}/drivers/fsl_lpuart_cmsis.c"
"${ProjDirPath}/drivers/fsl_lpuart.h"
"${ProjDirPath}/drivers/fsl_lpuart.c"
"${ProjDirPath}/drivers/fsl_lpspi_edma.h"
"${ProjDirPath}/drivers/fsl_lpspi_edma.c"
"${ProjDirPath}/drivers/fsl_lpspi_cmsis.h"
"${ProjDirPath}/drivers/fsl_lpspi_cmsis.c"
"${ProjDirPath}/drivers/fsl_lpspi.h"
"${ProjDirPath}/drivers/fsl_lpspi.c"
"${ProjDirPath}/drivers/fsl_lpi2c_edma.h"
"${ProjDirPath}/drivers/fsl_lpi2c_edma.c"
"${ProjDirPath}/drivers/fsl_lpi2c_cmsis.h"
"${ProjDirPath}/drivers/fsl_lpi2c_cmsis.c"
"${ProjDirPath}/drivers/fsl_lpi2c.h"
"${ProjDirPath}/drivers/fsl_lpi2c.c"
"${ProjDirPath}/drivers/fsl_lpflexcomm.h"
"${ProjDirPath}/drivers/fsl_lpflexcomm.c"
"${ProjDirPath}/drivers/fsl_lpadc.h"
"${ProjDirPath}/drivers/fsl_lpadc.c"
"${ProjDirPath}/drivers/fsl_gpio_cmsis.h"
"${ProjDirPath}/drivers/fsl_gpio_cmsis.c"
"${ProjDirPath}/drivers/fsl_gpio.h"
"${ProjDirPath}/drivers/fsl_gpio.c"
"${ProjDirPath}/drivers/fsl_enet.h"
"${ProjDirPath}/drivers/fsl_enet.c"
"${ProjDirPath}/drivers/fsl_edma_soc.h"
"${ProjDirPath}/drivers/fsl_edma_soc.c"
"${ProjDirPath}/drivers/fsl_edma_core.h"
"${ProjDirPath}/drivers/fsl_edma.h"
"${ProjDirPath}/drivers/fsl_edma.c"
"${ProjDirPath}/drivers/fsl_common_arm.h"
"${ProjDirPath}/drivers/fsl_common_arm.c"
"${ProjDirPath}/drivers/fsl_common.h"
"${ProjDirPath}/drivers/fsl_common.c"
"${ProjDirPath}/drivers/fsl_clock.h"
"${ProjDirPath}/drivers/fsl_clock.c"
"${ProjDirPath}/drivers/My_ethrnet.h"
"${ProjDirPath}/drivers/My_ethrnet.c"
"${ProjDirPath}/drivers/My_Indectors_driver.h"
"${ProjDirPath}/drivers/My_Indectors_driver.c"
"${ProjDirPath}/drivers/My_I2C_driver.h"
"${ProjDirPath}/drivers/My_I2C_driver.c"
"${ProjDirPath}/drivers/My_I2C_bmp280.h"
"${ProjDirPath}/drivers/My_I2C_bmp280.c"
"${ProjDirPath}/drivers/My_I2C_DS3231.h"
"${ProjDirPath}/drivers/My_I2C_DS3231.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/timers.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/tasks.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/stream_buffer.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/queue.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/list.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/event_groups.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/croutine.c"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/timers.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/task.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/stream_buffer.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/stack_macros.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/semphr.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/queue.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/projdefs.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/portable.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/mpu_wrappers.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/mpu_syscall_numbers.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/mpu_prototypes.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/message_buffer.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/list.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/freertos_tasks_c_additions.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/event_groups.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/deprecated_definitions.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/croutine.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/atomic.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/StackMacros.h"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include/FreeRTOS.h"
"${ProjDirPath}/freertos/freertos-kernel/template/FreeRTOSConfig.h"
"${ProjDirPath}/freertos/freertos-kernel/portable/MemMang/heap_4.c"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.h"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure/mpu_wrappers_v2_asm.c"
"${ProjDirPath}/lwip/template/lwipopts.h"
"${ProjDirPath}/lwip/port/ethernetif_priv.h"
"${ProjDirPath}/lwip/port/ethernetif_mmac.h"
"${ProjDirPath}/lwip/port/ethernetif_mmac.c"
"${ProjDirPath}/lwip/port/ethernetif.h"
"${ProjDirPath}/lwip/port/ethernetif.c"
"${ProjDirPath}/lwip/port/enet_ethernetif_lpc.c"
"${ProjDirPath}/lwip/port/enet_ethernetif.c"
"${ProjDirPath}/lwip/port/enet_configchecks.h"
"${ProjDirPath}/lwip/doc/ZeroCopyRx.c"
"${ProjDirPath}/lwip/doc/NO_SYS_SampleCode.c"
"${ProjDirPath}/lwip/src/netif/zepif.c"
"${ProjDirPath}/lwip/src/netif/slipif.c"
"${ProjDirPath}/lwip/src/netif/lowpan6_common.c"
"${ProjDirPath}/lwip/src/netif/lowpan6_ble.c"
"${ProjDirPath}/lwip/src/netif/lowpan6.c"
"${ProjDirPath}/lwip/src/netif/ethernet.c"
"${ProjDirPath}/lwip/src/netif/bridgeif_fdb.c"
"${ProjDirPath}/lwip/src/netif/bridgeif.c"
"${ProjDirPath}/lwip/src/core/udp.c"
"${ProjDirPath}/lwip/src/core/timeouts.c"
"${ProjDirPath}/lwip/src/core/tcp_out.c"
"${ProjDirPath}/lwip/src/core/tcp_in.c"
"${ProjDirPath}/lwip/src/core/tcp.c"
"${ProjDirPath}/lwip/src/core/sys.c"
"${ProjDirPath}/lwip/src/core/stats.c"
"${ProjDirPath}/lwip/src/core/raw.c"
"${ProjDirPath}/lwip/src/core/pbuf.c"
"${ProjDirPath}/lwip/src/core/netif.c"
"${ProjDirPath}/lwip/src/core/memp.c"
"${ProjDirPath}/lwip/src/core/mem.c"
"${ProjDirPath}/lwip/src/core/ip.c"
"${ProjDirPath}/lwip/src/core/init.c"
"${ProjDirPath}/lwip/src/core/inet_chksum.c"
"${ProjDirPath}/lwip/src/core/dns.c"
"${ProjDirPath}/lwip/src/core/def.c"
"${ProjDirPath}/lwip/src/core/altcp_tcp.c"
"${ProjDirPath}/lwip/src/core/altcp_alloc.c"
"${ProjDirPath}/lwip/src/core/altcp.c"
"${ProjDirPath}/lwip/src/api/tcpip.c"
"${ProjDirPath}/lwip/src/api/sockets.c"
"${ProjDirPath}/lwip/src/api/netifapi.c"
"${ProjDirPath}/lwip/src/api/netdb.c"
"${ProjDirPath}/lwip/src/api/netbuf.c"
"${ProjDirPath}/lwip/src/api/if_api.c"
"${ProjDirPath}/lwip/src/api/err.c"
"${ProjDirPath}/lwip/src/api/api_msg.c"
"${ProjDirPath}/lwip/src/api/api_lib.c"
"${ProjDirPath}/lwip/port/arch/perf.h"
"${ProjDirPath}/lwip/port/arch/cc.h"
"${ProjDirPath}/lwip/doc/doxygen/main_page.h"
"${ProjDirPath}/lwip/src/netif/ppp/vj.c"
"${ProjDirPath}/lwip/src/netif/ppp/utils.c"
"${ProjDirPath}/lwip/src/netif/ppp/upap.c"
"${ProjDirPath}/lwip/src/netif/ppp/pppos.c"
"${ProjDirPath}/lwip/src/netif/ppp/pppol2tp.c"
"${ProjDirPath}/lwip/src/netif/ppp/pppoe.c"
"${ProjDirPath}/lwip/src/netif/ppp/pppcrypt.c"
"${ProjDirPath}/lwip/src/netif/ppp/pppapi.c"
"${ProjDirPath}/lwip/src/netif/ppp/ppp.c"
"${ProjDirPath}/lwip/src/netif/ppp/multilink.c"
"${ProjDirPath}/lwip/src/netif/ppp/mppe.c"
"${ProjDirPath}/lwip/src/netif/ppp/magic.c"
"${ProjDirPath}/lwip/src/netif/ppp/lcp.c"
"${ProjDirPath}/lwip/src/netif/ppp/ipv6cp.c"
"${ProjDirPath}/lwip/src/netif/ppp/ipcp.c"
"${ProjDirPath}/lwip/src/netif/ppp/fsm.c"
"${ProjDirPath}/lwip/src/netif/ppp/eui64.c"
"${ProjDirPath}/lwip/src/netif/ppp/ecp.c"
"${ProjDirPath}/lwip/src/netif/ppp/eap.c"
"${ProjDirPath}/lwip/src/netif/ppp/demand.c"
"${ProjDirPath}/lwip/src/netif/ppp/chap_ms.c"
"${ProjDirPath}/lwip/src/netif/ppp/chap-new.c"
"${ProjDirPath}/lwip/src/netif/ppp/chap-md5.c"
"${ProjDirPath}/lwip/src/netif/ppp/ccp.c"
"${ProjDirPath}/lwip/src/netif/ppp/auth.c"
"${ProjDirPath}/lwip/src/include/netif/zepif.h"
"${ProjDirPath}/lwip/src/include/netif/slipif.h"
"${ProjDirPath}/lwip/src/include/netif/lowpan6_opts.h"
"${ProjDirPath}/lwip/src/include/netif/lowpan6_common.h"
"${ProjDirPath}/lwip/src/include/netif/lowpan6_ble.h"
"${ProjDirPath}/lwip/src/include/netif/lowpan6.h"
"${ProjDirPath}/lwip/src/include/netif/ieee802154.h"
"${ProjDirPath}/lwip/src/include/netif/ethernet.h"
"${ProjDirPath}/lwip/src/include/netif/etharp.h"
"${ProjDirPath}/lwip/src/include/netif/bridgeif_opts.h"
"${ProjDirPath}/lwip/src/include/netif/bridgeif.h"
"${ProjDirPath}/lwip/src/include/lwip/udp.h"
"${ProjDirPath}/lwip/src/include/lwip/timeouts.h"
"${ProjDirPath}/lwip/src/include/lwip/tcpip.h"
"${ProjDirPath}/lwip/src/include/lwip/tcpbase.h"
"${ProjDirPath}/lwip/src/include/lwip/tcp.h"
"${ProjDirPath}/lwip/src/include/lwip/sys.h"
"${ProjDirPath}/lwip/src/include/lwip/stats.h"
"${ProjDirPath}/lwip/src/include/lwip/sockets.h"
"${ProjDirPath}/lwip/src/include/lwip/snmp.h"
"${ProjDirPath}/lwip/src/include/lwip/sio.h"
"${ProjDirPath}/lwip/src/include/lwip/raw.h"
"${ProjDirPath}/lwip/src/include/lwip/pbuf.h"
"${ProjDirPath}/lwip/src/include/lwip/opt.h"
"${ProjDirPath}/lwip/src/include/lwip/netifapi.h"
"${ProjDirPath}/lwip/src/include/lwip/netif.h"
"${ProjDirPath}/lwip/src/include/lwip/netdb.h"
"${ProjDirPath}/lwip/src/include/lwip/netbuf.h"
"${ProjDirPath}/lwip/src/include/lwip/nd6.h"
"${ProjDirPath}/lwip/src/include/lwip/mld6.h"
"${ProjDirPath}/lwip/src/include/lwip/memp.h"
"${ProjDirPath}/lwip/src/include/lwip/mem.h"
"${ProjDirPath}/lwip/src/include/lwip/ip_addr.h"
"${ProjDirPath}/lwip/src/include/lwip/ip6_zone.h"
"${ProjDirPath}/lwip/src/include/lwip/ip6_frag.h"
"${ProjDirPath}/lwip/src/include/lwip/ip6_addr.h"
"${ProjDirPath}/lwip/src/include/lwip/ip6.h"
"${ProjDirPath}/lwip/src/include/lwip/ip4_frag.h"
"${ProjDirPath}/lwip/src/include/lwip/ip4_addr.h"
"${ProjDirPath}/lwip/src/include/lwip/ip4.h"
"${ProjDirPath}/lwip/src/include/lwip/ip.h"
"${ProjDirPath}/lwip/src/include/lwip/init.h"
"${ProjDirPath}/lwip/src/include/lwip/inet_chksum.h"
"${ProjDirPath}/lwip/src/include/lwip/inet.h"
"${ProjDirPath}/lwip/src/include/lwip/igmp.h"
"${ProjDirPath}/lwip/src/include/lwip/if_api.h"
"${ProjDirPath}/lwip/src/include/lwip/icmp6.h"
"${ProjDirPath}/lwip/src/include/lwip/icmp.h"
"${ProjDirPath}/lwip/src/include/lwip/ethip6.h"
"${ProjDirPath}/lwip/src/include/lwip/etharp.h"
"${ProjDirPath}/lwip/src/include/lwip/errno.h"
"${ProjDirPath}/lwip/src/include/lwip/err.h"
"${ProjDirPath}/lwip/src/include/lwip/dns.h"
"${ProjDirPath}/lwip/src/include/lwip/dhcp6.h"
"${ProjDirPath}/lwip/src/include/lwip/dhcp.h"
"${ProjDirPath}/lwip/src/include/lwip/def.h"
"${ProjDirPath}/lwip/src/include/lwip/debug.h"
"${ProjDirPath}/lwip/src/include/lwip/autoip.h"
"${ProjDirPath}/lwip/src/include/lwip/arch.h"
"${ProjDirPath}/lwip/src/include/lwip/api.h"
"${ProjDirPath}/lwip/src/include/lwip/altcp_tls.h"
"${ProjDirPath}/lwip/src/include/lwip/altcp_tcp.h"
"${ProjDirPath}/lwip/src/include/lwip/altcp.h"
"${ProjDirPath}/lwip/src/include/lwip/acd.h"
"${ProjDirPath}/lwip/src/apps/mdns/mdns_out.c"
"${ProjDirPath}/lwip/src/apps/mdns/mdns_domain.c"
"${ProjDirPath}/lwip/src/apps/mdns/mdns.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_ws_prv.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_ws_api.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_ws.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_ws.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_utf8.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_utf8.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_tls.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_tls.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_task.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_supp.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_supp.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_sha1.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_sha1.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_script.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_script.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_prv.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_port.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_fs.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_fs.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_config.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_base64.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv_base64.c"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv.h"
"${ProjDirPath}/lwip/src/apps/httpsrv/httpsrv.c"
"${ProjDirPath}/lwip/src/core/ipv6/nd6.c"
"${ProjDirPath}/lwip/src/core/ipv6/mld6.c"
"${ProjDirPath}/lwip/src/core/ipv6/ip6_frag.c"
"${ProjDirPath}/lwip/src/core/ipv6/ip6_addr.c"
"${ProjDirPath}/lwip/src/core/ipv6/ip6.c"
"${ProjDirPath}/lwip/src/core/ipv6/inet6.c"
"${ProjDirPath}/lwip/src/core/ipv6/icmp6.c"
"${ProjDirPath}/lwip/src/core/ipv6/ethip6.c"
"${ProjDirPath}/lwip/src/core/ipv6/dhcp6.c"
"${ProjDirPath}/lwip/src/core/ipv4/ip4_frag.c"
"${ProjDirPath}/lwip/src/core/ipv4/ip4_addr.c"
"${ProjDirPath}/lwip/src/core/ipv4/ip4.c"
"${ProjDirPath}/lwip/src/core/ipv4/igmp.c"
"${ProjDirPath}/lwip/src/core/ipv4/icmp.c"
"${ProjDirPath}/lwip/src/core/ipv4/etharp.c"
"${ProjDirPath}/lwip/src/core/ipv4/dhcp.c"
"${ProjDirPath}/lwip/src/core/ipv4/autoip.c"
"${ProjDirPath}/lwip/src/core/ipv4/acd.c"
"${ProjDirPath}/lwip/port/sys_arch/dynamic/sys_arch.c"
"${ProjDirPath}/lwip/src/netif/ppp/polarssl/sha1.c"
"${ProjDirPath}/lwip/src/netif/ppp/polarssl/md5.c"
"${ProjDirPath}/lwip/src/netif/ppp/polarssl/md4.c"
"${ProjDirPath}/lwip/src/netif/ppp/polarssl/des.c"
"${ProjDirPath}/lwip/src/netif/ppp/polarssl/arc4.c"
"${ProjDirPath}/lwip/src/include/netif/ppp/vj.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/upap.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppos.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppol2tp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppoe.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppdebug.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppcrypt.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/pppapi.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ppp_opts.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ppp_impl.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ppp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/mppe.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/magic.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/lcp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ipv6cp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ipcp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/fsm.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/eui64.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ecp.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/eap.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/chap_ms.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/chap-new.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/chap-md5.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/ccp.h"
"${ProjDirPath}/lwip/src/include/compat/stdc/errno.h"
"${ProjDirPath}/lwip/src/include/compat/posix/netdb.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/tcpip_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/tcp_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/sockets_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/raw_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/nd6_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/memp_std.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/memp_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/mem_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/api_msg.h"
"${ProjDirPath}/lwip/src/include/lwip/priv/altcp_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/apps/mdns_priv.h"
"${ProjDirPath}/lwip/src/include/lwip/apps/mdns_out.h"
"${ProjDirPath}/lwip/src/include/lwip/apps/mdns_opts.h"
"${ProjDirPath}/lwip/src/include/lwip/apps/mdns_domain.h"
"${ProjDirPath}/lwip/src/include/lwip/apps/mdns.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/udp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/tcp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/nd6.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/mld6.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/ip6.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/ip4.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/ip.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/igmp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/ieee.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/icmp6.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/icmp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/iana.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/ethernet.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/etharp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/dns.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/dhcp6.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/dhcp.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/autoip.h"
"${ProjDirPath}/lwip/src/include/lwip/prot/acd.h"
"${ProjDirPath}/lwip/port/sys_arch/dynamic/arch/sys_arch.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/polarssl/sha1.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/polarssl/md5.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/polarssl/md4.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/polarssl/des.h"
"${ProjDirPath}/lwip/src/include/netif/ppp/polarssl/arc4.h"
"${ProjDirPath}/lwip/src/include/compat/posix/sys/socket.h"
"${ProjDirPath}/lwip/src/include/compat/posix/net/if.h"
"${ProjDirPath}/lwip/src/include/compat/posix/arpa/inet.h"
"${ProjDirPath}/phy/fsl_phylan8741.h"
"${ProjDirPath}/phy/fsl_phylan8741.c"
"${ProjDirPath}/services/ethrnet_service/ethrnet_service.h"
"${ProjDirPath}/services/ethrnet_service/ethrnet_service.c"
"${ProjDirPath}/services/Indectors_service/Indectors_service.h"
"${ProjDirPath}/services/Indectors_service/Indectors_service.c"
"${ProjDirPath}/services/Analog_service/Analog_service.h"
"${ProjDirPath}/services/Analog_service/Analog_service.c"
"${ProjDirPath}/services/HealthMonitor_service/HealthMonitor_service.h"
"${ProjDirPath}/services/HealthMonitor_service/HealthMonitor_service.c"
"${ProjDirPath}/source/task_config.h"
"${ProjDirPath}/source/semihost_hardfault.c"
"${ProjDirPath}/source/MCXN947_Web_Based_Data_Logger.c"
"${ProjDirPath}/source/FreeRTOSConfig_Gen.h"
"${ProjDirPath}/startup/startup_mcxn947_cm33_core0.c"
"${ProjDirPath}/startup/boot_multicore_slave.h"
"${ProjDirPath}/startup/boot_multicore_slave.c"
"${ProjDirPath}/utilities/fsl_assert.h"
"${ProjDirPath}/utilities/fsl_assert.c"
"${ProjDirPath}/utilities/str/fsl_str.h"
"${ProjDirPath}/utilities/str/fsl_str.c"
"${ProjDirPath}/utilities/debug_console/fsl_debug_console.h"
"${ProjDirPath}/utilities/debug_console/fsl_debug_console.c"
"${ProjDirPath}/utilities/debug_console/config/fsl_debug_console_conf.h"
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set_target_properties(${MCUX_SDK_PROJECT_NAME} PROPERTIES SUFFIX ".axf")
endif()

if(${LIBRARY_TYPE} STREQUAL "REDLIB")
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE $ENV{ARMGCC_DIR}/redlib/include)
endif()

set(asm_include_directories "${ProjDirPath}/drivers"
"${ProjDirPath}/device"
"${ProjDirPath}/utilities/debug_console"
"${ProjDirPath}/component/uart"
"${ProjDirPath}/utilities/debug_console/config"
"${ProjDirPath}/component/serial_manager"
"${ProjDirPath}/component/lists"
"${ProjDirPath}/device/periph"
"${ProjDirPath}/utilities"
"${ProjDirPath}/CMSIS"
"${ProjDirPath}/CMSIS/m-profile"
"${ProjDirPath}/utilities/str"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include"
"${ProjDirPath}/freertos/freertos-kernel/include"
"${ProjDirPath}/lwip/port"
"${ProjDirPath}/lwip/src/include"
"${ProjDirPath}/lwip/port/sys_arch/dynamic"
"${ProjDirPath}/lwip/src/apps/httpsrv"
"${ProjDirPath}/phy"
"${ProjDirPath}/component/phy"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
"${ProjDirPath}/component/silicon_id"
"${ProjDirPath}/component"
"${ProjDirPath}/component/gpio"
"${ProjDirPath}/CMSIS_driver/Include/GPIO"
"${ProjDirPath}/CMSIS_driver/Include"
"${ProjDirPath}/lwip/template"
"${ProjDirPath}/board"
"${ProjDirPath}/freertos/freertos-kernel/template"
"${ProjDirPath}/source"
"${ProjDirPath}/app"
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:ASM>:${asm_include_directories}>)

set(c_include_directories "${ProjDirPath}/drivers"
"${ProjDirPath}/device"
"${ProjDirPath}/utilities/debug_console"
"${ProjDirPath}/component/uart"
"${ProjDirPath}/utilities/debug_console/config"
"${ProjDirPath}/component/serial_manager"
"${ProjDirPath}/component/lists"
"${ProjDirPath}/device/periph"
"${ProjDirPath}/utilities"
"${ProjDirPath}/CMSIS"
"${ProjDirPath}/CMSIS/m-profile"
"${ProjDirPath}/utilities/str"
"${ProjDirPath}/freertos/freertos-kernel-upstream/include"
"${ProjDirPath}/freertos/freertos-kernel/include"
"${ProjDirPath}/lwip/port"
"${ProjDirPath}/lwip/src/include"
"${ProjDirPath}/lwip/port/sys_arch/dynamic"
"${ProjDirPath}/lwip/src/apps/httpsrv"
"${ProjDirPath}/phy"
"${ProjDirPath}/component/phy"
"${ProjDirPath}/freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
"${ProjDirPath}/component/silicon_id"
"${ProjDirPath}/component"
"${ProjDirPath}/component/gpio"
"${ProjDirPath}/CMSIS_driver/Include"
"${ProjDirPath}/CMSIS_driver/Include/GPIO"
"${ProjDirPath}/board"
"${ProjDirPath}/lwip/template"
"${ProjDirPath}/services/Analog_service"
"${ProjDirPath}/services/HealthMonitor_service"
"${ProjDirPath}/services/Indectors_service"
"${ProjDirPath}/app/Led_Indicators"
"${ProjDirPath}/services/ethrnet_service"
"${ProjDirPath}/services/I2C_service"
"${ProjDirPath}/app/Temp"
"${ProjDirPath}/freertos/freertos-kernel/template"
"${ProjDirPath}/source"
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:C>:${c_include_directories}>)

set(cpp_include_directories "")

target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${cpp_include_directories}>)

set(include_files "")

target_precompile_headers(${MCUX_SDK_PROJECT_NAME} PRIVATE ${include_files})

set(link_directories "")

set(link_libraries "")

target_link_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE ${link_directories})
target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE -Wl,--start-group)
target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE ${TARGET_LINK_SYSTEM_LIBRARIES} ${link_libraries})
target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE -Wl,--end-group)

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
	add_custom_command(
		TARGET ${MCUX_SDK_PROJECT_NAME}
		POST_BUILD
		COMMAND $ENV{ARMGCC_DIR}/bin/arm-none-eabi-size "$<TARGET_FILE_NAME:${MCUX_SDK_PROJECT_NAME}>" || true
	)
endif()

